export const COLLAGE_DEFAULT_IMAGE_COUNT = 4;
export const COLLAGE_DEFAULT_ROWS = 3;
export const COLLAGE_DEFAULT_COLS = 3;
export const COLLAGE_MAX_IMAGES = 30;
export const COLLAGE_MAX_ROWS = 96;
export const COLLAGE_MAX_COLS = 96;
export const COLLAGE_DEFAULT_STAGE_WIDTH = 960;
export const COLLAGE_DEFAULT_STAGE_HEIGHT = 540;
export const COLLAGE_STAGE_MIN_WIDTH = 360;
export const COLLAGE_STAGE_MAX_WIDTH = 3840;
export const COLLAGE_STAGE_MIN_HEIGHT = 240;
export const COLLAGE_STAGE_MAX_HEIGHT = 2160;
export const COLLAGE_PIECE_OVERLAP_PX = 1;

export const COLLAGE_RATIO_MIN = COLLAGE_STAGE_MIN_HEIGHT / COLLAGE_STAGE_MAX_WIDTH;
export const COLLAGE_RATIO_MAX = COLLAGE_STAGE_MAX_HEIGHT / COLLAGE_STAGE_MIN_WIDTH;
